[General]
{{general}}
dns-server = system
include = private.conf
update-url = https://ghproxy.net/https://raw.githubusercontent.com/luoluodaduan/Rules/main/gen/black-tiktok.conf
[Rule]
{{private}}
{{tiktok}}
{{telegram}}
DOMAIN-SET,https://ghproxy.net/https://raw.githubusercontent.com/luoluodaduan/Rules/main/gen/apple.txt,DIRECT
{{custom}}
{{proxy}}
FINAL,DIRECT
[Host]
localhost = 127.0.0.1
[URL Rewrite]
{{rewriteplus}}
