[General]
{{general}}
dns-server = system
include = private.conf
update-url = https://raw.gitmirror.com/luoluodaduan/Rules/main/gen/white-ad-tiktok.conf
[Rule]
{{private}}
{{tiktok}}
{{telegram}}
DOMAIN-SET,https://raw.gitmirror.com/luoluodaduan/Rules/main/gen/apple.txt,DIRECT
{{custom}}
{{proxy}}
DOMAIN-SET,https://raw.gitmirror.com/luoluodaduan/Rules/main/gen/direct.txt,DIRECT
RULE-SET,https://raw.gitmirror.com/luoluodaduan/Rules/main/gen/cnip.txt,DIRECT
FINAL,PROXY
[Host]
localhost = 127.0.0.1
[URL Rewrite]
{{rewriteplus}}
