# update at {{build_time}}
[General]
{{general}}
dns-server = system
fallback-dns-server = 223.5.5.5:53, 119.29.29.29:53
update-url = https://ghproxy.net/https://raw.githubusercontent.com/luoluodaduan/Rules/main/gen/white-ad.conf
[Rule]
{{private}}
DOMAIN-SET,https://ghproxy.net/https://raw.githubusercontent.com/luoluodaduan/Rules/main/gen/reject.txt,REJECT
{{custom}}
DOMAIN,netease.ugcvideoss.ourdvs.com,NMUSIC
DOMAIN-SUFFIX,163yun.com,NMUSIC
DOMAIN-SUFFIX,api.iplay.163.com,NMUSIC
DOMAIN-SUFFIX,hz.netease.com,NMUSIC
DOMAIN-SUFFIX,mam.netease.com,NMUSIC
DOMAIN-SUFFIX,music.126.com,NMUSIC
DOMAIN-SUFFIX,music.126.net,NMUSIC
DOMAIN-SUFFIX,music.163.com,NMUSIC
DOMAIN-SUFFIX,music.163.com.163jiasu.com,NMUSIC
DOMAIN-SUFFIX,yun-app.net,NMUSIC
USER-AGENT,%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90*,NMUSIC
USER-AGENT,NeteaseMusic*,NMUSIC
DOMAIN-SET,https://ghproxy.net/https://raw.githubusercontent.com/luoluodaduan/Rules/main/gen/apple.txt,DIRECT
DOMAIN-SET,https://ghproxy.net/https://raw.githubusercontent.com/luoluodaduan/Rules/main/gen/direct.txt,DIRECT
DOMAIN-SET,https://ghproxy.net/https://raw.githubusercontent.com/luoluodaduan/Rules/main/gen/proxy.txt,PROXY
{{telegram}}
RULE-SET,https://ghproxy.net/https://raw.githubusercontent.com/luoluodaduan/Rules/main/gen/cnip.txt,DIRECT
FINAL,PROXY
[Host]
localhost = 127.0.0.1
[URL Rewrite]
{{rewrite}}
